export const ERROR_CODES = {
	UNAUTHENTICATED: 'UNAUTHENTICATED',
	CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
	CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
	TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
